name: Draft PR for New Branches
on:
  workflow_dispatch:
  create:
    ref_type: branch    
    branches-ignore:
      - dev**
      - newdev**
      - main
      - master
jobs:
  new_branch_pr:
    if: github.repository == 'Snuffy2/places'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Show Branch Name
        run: echo ${GITHUB_REF##*/}
      - name: Show Ref
        run: echo ${{ github.ref }}
      - name: Show Git Config
        run: cat .git/config
      - name: Create and Checkout the New branch
        run: git checkout ${GITHUB_REF##*/}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Create Empty Commit
        run: git commit --allow-empty -m "Empty commit"
      - name: Push Empty Commit
        run: git push
      - name: Set Upstream
        run: git remote add upstream https://github.com/custom-components/places.git
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
      - name: Show Git Config
        run: cat .git/config
      - name: Create Pull Request
        run: gh pr create -d -B master -b "${GITHUB_REF##*/}" -t "${GITHUB_REF##*/}"
        env:
          GITHUB_TOKEN: ${{ secrets.CPR }}
          GH_TOKEN: ${{ secrets.CPR }}
