name: Create New Dev Branch and PR
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  new_dev_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Create and Checkout New Dev branch
        run: git checkout -b dev
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Empty Commit
        run: git commit --allow-empty -m "Empty commit"
      - name: Push Commit
        run: git push --set-upstream origin dev
      - name: Create Pull Request
        run: gh pr create -d -B ${{ github.event.repository.default_branch }} -l ignore-for-release -b "Dev PR Release" -t "Dev PR Release"
        env:
          GITHUB_TOKEN: ${{ secrets.CPR }}
