name: Create Zip on Release
on:
  workflow_dispatch:
  release:
    types: [published, edited]
jobs:
  create_zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.2
    - name: Update Version in Manifest
      if: ${{ github.event_name == 'release' }}
      run: |
        sed -i 's/\"version\"\s*\:\s*\".*\"/\"version\"\:\"${{ github.ref_name }}\"/g' ./custom_components/places/manifest.json
    - name: Update Version in const.py
      if: ${{ github.event_name == 'release' }}
      run: |
        sed -i 's/VERSION \= \".*\"/VERSION \= \"${{ github.ref_name }}\"/' ./custom_components/places/const.py        
    - name: Commit & Push Version Changes
      if: ${{ github.event_name == 'release' }}
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master'
        message: 'Updating to version ${{ github.ref_name }}'
    - name: Create Zip
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'places.zip'
        directory: ./custom_components/places
    - name: Upload Zip to Release
      if: ${{ github.event_name == 'release' }}
      uses: Roang-zero1/github-upload-release-artifacts-action@v3.0.0
      with:
        args: ./custom_components/places/places.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Add Zip to Action
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/upload-artifact@v4.3.2
      with:
        name: places
        path: ./custom_components/places/places.zip
        if-no-files-found: error
